language: node_js
node_js:
  - '0.10'
  - '4'
  - '5'
  - '6'
  - '7'
  - '8'
before_install:
  - 'currentfolder=${PWD##*/}'
  - >-
    if [ "$currentfolder" != 'semver-date' ]; then cd .. && eval "mv
    $currentfolder semver-date" && cd semver-date; fi
